# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c2s.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='c2s.proto',
  package='de.tu_darmstadt.seemoo.nfcgate.network.c2s',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tc2s.proto\x12*de.tu_darmstadt.seemoo.nfcgate.network.c2s\"\xa3\x01\n\nServerData\x12M\n\x06opcode\x18\x01 \x01(\x0e\x32=.de.tu_darmstadt.seemoo.nfcgate.network.c2s.ServerData.Opcode\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"8\n\x06Opcode\x12\n\n\x06OP_PSH\x10\x00\x12\n\n\x06OP_SYN\x10\x01\x12\n\n\x06OP_ACK\x10\x02\x12\n\n\x06OP_FIN\x10\x03\x62\x06proto3')
)



_SERVERDATA_OPCODE = _descriptor.EnumDescriptor(
  name='Opcode',
  full_name='de.tu_darmstadt.seemoo.nfcgate.network.c2s.ServerData.Opcode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OP_PSH', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OP_SYN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OP_ACK', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OP_FIN', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=165,
  serialized_end=221,
)
_sym_db.RegisterEnumDescriptor(_SERVERDATA_OPCODE)


_SERVERDATA = _descriptor.Descriptor(
  name='ServerData',
  full_name='de.tu_darmstadt.seemoo.nfcgate.network.c2s.ServerData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opcode', full_name='de.tu_darmstadt.seemoo.nfcgate.network.c2s.ServerData.opcode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='de.tu_darmstadt.seemoo.nfcgate.network.c2s.ServerData.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVERDATA_OPCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=221,
)

_SERVERDATA.fields_by_name['opcode'].enum_type = _SERVERDATA_OPCODE
_SERVERDATA_OPCODE.containing_type = _SERVERDATA
DESCRIPTOR.message_types_by_name['ServerData'] = _SERVERDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerData = _reflection.GeneratedProtocolMessageType('ServerData', (_message.Message,), dict(
  DESCRIPTOR = _SERVERDATA,
  __module__ = 'c2s_pb2'
  # @@protoc_insertion_point(class_scope:de.tu_darmstadt.seemoo.nfcgate.network.c2s.ServerData)
  ))
_sym_db.RegisterMessage(ServerData)


# @@protoc_insertion_point(module_scope)
