# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metaMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import c2s_pb2 as c2s__pb2
import c2c_pb2 as c2c__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metaMessage.proto',
  package='tud.seemuh.nfcgate.network.meta',
  syntax='proto2',
  serialized_pb=_b('\n\x11metaMessage.proto\x12\x1ftud.seemuh.nfcgate.network.meta\x1a\tc2s.proto\x1a\tc2c.proto\"\xb8\x02\n\x07Wrapper\x12:\n\x07NFCData\x18\x02 \x01(\x0b\x32\'.tud.seemuh.nfcgate.network.c2c.NFCDataH\x00\x12:\n\x07\x41nticol\x18\x03 \x01(\x0b\x32\'.tud.seemuh.nfcgate.network.c2c.AnticolH\x00\x12\x38\n\x06Status\x18\x04 \x01(\x0b\x32&.tud.seemuh.nfcgate.network.c2c.StatusH\x00\x12\x34\n\x04\x44\x61ta\x18\x05 \x01(\x0b\x32$.tud.seemuh.nfcgate.network.c2s.DataH\x00\x12:\n\x07Session\x18\x06 \x01(\x0b\x32\'.tud.seemuh.nfcgate.network.c2s.SessionH\x00\x42\t\n\x07message')
  ,
  dependencies=[c2s__pb2.DESCRIPTOR,c2c__pb2.DESCRIPTOR,])




_WRAPPER = _descriptor.Descriptor(
  name='Wrapper',
  full_name='tud.seemuh.nfcgate.network.meta.Wrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='NFCData', full_name='tud.seemuh.nfcgate.network.meta.Wrapper.NFCData', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Anticol', full_name='tud.seemuh.nfcgate.network.meta.Wrapper.Anticol', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Status', full_name='tud.seemuh.nfcgate.network.meta.Wrapper.Status', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Data', full_name='tud.seemuh.nfcgate.network.meta.Wrapper.Data', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Session', full_name='tud.seemuh.nfcgate.network.meta.Wrapper.Session', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='tud.seemuh.nfcgate.network.meta.Wrapper.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=77,
  serialized_end=389,
)

_WRAPPER.fields_by_name['NFCData'].message_type = c2c__pb2._NFCDATA
_WRAPPER.fields_by_name['Anticol'].message_type = c2c__pb2._ANTICOL
_WRAPPER.fields_by_name['Status'].message_type = c2c__pb2._STATUS
_WRAPPER.fields_by_name['Data'].message_type = c2s__pb2._DATA
_WRAPPER.fields_by_name['Session'].message_type = c2s__pb2._SESSION
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['NFCData'])
_WRAPPER.fields_by_name['NFCData'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['Anticol'])
_WRAPPER.fields_by_name['Anticol'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['Status'])
_WRAPPER.fields_by_name['Status'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['Data'])
_WRAPPER.fields_by_name['Data'].containing_oneof = _WRAPPER.oneofs_by_name['message']
_WRAPPER.oneofs_by_name['message'].fields.append(
  _WRAPPER.fields_by_name['Session'])
_WRAPPER.fields_by_name['Session'].containing_oneof = _WRAPPER.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['Wrapper'] = _WRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Wrapper = _reflection.GeneratedProtocolMessageType('Wrapper', (_message.Message,), dict(
  DESCRIPTOR = _WRAPPER,
  __module__ = 'metaMessage_pb2'
  # @@protoc_insertion_point(class_scope:tud.seemuh.nfcgate.network.meta.Wrapper)
  ))
_sym_db.RegisterMessage(Wrapper)


# @@protoc_insertion_point(module_scope)
